# name: CICD TEST Workflow

# on:
#   push:
#     branches:
#       - master

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20.19.0'   # You can pick another version if needed

#       - name: Run JavaScript file
#         run: node main.js
# ===============================
# name: CICD TEST Workflow

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build Docker image
#         run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-js:latest .

#       - name: List Docker images (for verification)
#         run: docker images

#       - name: Push Docker image to Docker Hub
#         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-js:latest

# =============================================
name: CICD TEST Workflow

on:
  push:
    branches:
      - master

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image (with tests included)
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-js:latest .

      # Run tests inside Docker container
      - name: Run tests inside container
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-js:latest npm test

      # List Docker images (for verification)
      - name: List Docker images
        run: docker images

      # Push Docker image to Docker Hub (only if tests pass)
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-js:latest
      